/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    blank?: boolean;
    _type: "link";
    _key: string;
  } | {
    reference?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "work";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "recording";
    } | {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "review";
    };
    _type: "internalLink";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  caption?: string;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  body?: BlockContent;
  vitalInfo?: BlockContent;
  otherLinks?: BlockContent;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    credits?: string;
    _type: "image";
    _key: string;
  }>;
  streamEmbed?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Performance = {
  _id: string;
  _type: "performance";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  programTitle?: string;
  composer?: string;
  context?: string;
  ensemble?: string;
  instrumentation?: string;
  personnel?: string;
  programWork?: string;
  programDate?: string;
};

export type Work = {
  _id: string;
  _type: "work";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  parent?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "work";
  };
  duration?: string;
  isCompleted?: boolean;
  completionDate?: string;
  instrumentation?: Array<{
    instrument?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "instrument";
    };
    quantity?: number;
    _key: string;
  }>;
  useAbbreviatedInstrumentation?: boolean;
  abbreviatedInstrumentation?: string;
  hasAlternativeInstrumentation?: boolean;
  alternativeInstrumentation?: Array<{
    instrument?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "instrument";
    };
    quantity?: number;
    _key: string;
  }>;
  inlineNotes?: string;
  programNote?: BlockContent;
  miscellaneousNotes?: BlockContent;
  soundCloudEmbedUrl?: string;
  audio?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    date?: string;
    performers?: string;
    location?: string;
    credits?: string;
    _type: "file";
    _key: string;
  }>;
  videos?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    title?: string;
    date?: string;
    performers?: string;
    location?: string;
    credits?: string;
    _type: "file";
    _key: string;
  }>;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    date?: string;
    performers?: string;
    location?: string;
    credits?: string;
    _type: "image";
    _key: string;
  }>;
  isOnCd?: boolean;
  cd?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "recording";
  };
  hasElectronics?: boolean;
  electronicsDescription?: BlockContent;
  commissionInfo?: string;
  dedication?: string;
  isPublished?: boolean;
  publisher?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "publisher";
  };
  publisherLink?: string;
  scoreSampleLink?: string;
  score?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
  };
  downloads?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
    _key: string;
  }>;
  isPasswordProtected?: boolean;
  passwordOverride?: string;
  publicDownloads?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
    };
    media?: unknown;
    _type: "file";
    _key: string;
  }>;
};

export type Publisher = {
  _id: string;
  _type: "publisher";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  website?: string;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type Review = {
  _id: string;
  _type: "review";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  reviewType?: "cd" | "performance" | "news";
  relatedWorks?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "work";
  }>;
  relatedRecordings?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "recording";
  }>;
  body?: BlockContent;
  excerpt?: BlockContent;
  reviewDate?: string;
  source?: string;
  author?: string;
  reviewLink?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Recording = {
  _id: string;
  _type: "recording";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  recordLabel?: string;
  catalogNumber?: string;
  releaseDate?: string;
  albumLink?: string;
  purchaseLink?: string;
  albumArt?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  pieces?: Array<{
    piece?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "work";
    };
    performers?: string;
    _key: string;
  }>;
  isFeatured?: boolean;
};

export type Instrument = {
  _id: string;
  _type: "instrument";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  abbreviation?: string;
  category?: "woodwinds" | "brass" | "strings" | "percussion" | "keyboard" | "voice" | "electronics" | "other";
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes = BlockContent | AboutPage | SanityImageCrop | SanityImageHotspot | Performance | Work | Publisher | Review | Slug | Recording | Instrument | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageMetadata | SanityFileAsset | SanityAssetSourceData | SanityImageAsset | Geopoint;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/app/works/page.tsx
// Variable: WORKS_LISTING_QUERY
// Query: *[_type == "work" && !defined(parent)]{    _id,  title,  slug,  completionDate,  isCompleted,  duration,  instrumentation[] {    _key,    quantity,    instrument -> { name }  },  useAbbreviatedInstrumentation,  abbreviatedInstrumentation,  inlineNotes,  commissionInfo,  "children": *[_type == "work" && parent._ref == ^._id]{      _id,  title,  slug,  completionDate,  isCompleted,  duration,  instrumentation[] {    _key,    quantity,    instrument -> { name }  },  useAbbreviatedInstrumentation,  abbreviatedInstrumentation,  inlineNotes,  commissionInfo  }}
export type WORKS_LISTING_QUERYResult = Array<{
  _id: string;
  title: string | null;
  slug: Slug | null;
  completionDate: string | null;
  isCompleted: boolean | null;
  duration: string | null;
  instrumentation: Array<{
    _key: string;
    quantity: number | null;
    instrument: {
      name: string | null;
    } | null;
  }> | null;
  useAbbreviatedInstrumentation: boolean | null;
  abbreviatedInstrumentation: string | null;
  inlineNotes: string | null;
  commissionInfo: string | null;
  children: Array<{
    _id: string;
    title: string | null;
    slug: Slug | null;
    completionDate: string | null;
    isCompleted: boolean | null;
    duration: string | null;
    instrumentation: Array<{
      _key: string;
      quantity: number | null;
      instrument: {
        name: string | null;
      } | null;
    }> | null;
    useAbbreviatedInstrumentation: boolean | null;
    abbreviatedInstrumentation: string | null;
    inlineNotes: string | null;
    commissionInfo: string | null;
  }>;
}>;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"work\" && !defined(parent)]{\n  \n  _id,\n  title,\n  slug,\n  completionDate,\n  isCompleted,\n  duration,\n  instrumentation[] {\n    _key,\n    quantity,\n    instrument -> { name }\n  },\n  useAbbreviatedInstrumentation,\n  abbreviatedInstrumentation,\n  inlineNotes,\n  commissionInfo\n,\n  \"children\": *[_type == \"work\" && parent._ref == ^._id]{\n    \n  _id,\n  title,\n  slug,\n  completionDate,\n  isCompleted,\n  duration,\n  instrumentation[] {\n    _key,\n    quantity,\n    instrument -> { name }\n  },\n  useAbbreviatedInstrumentation,\n  abbreviatedInstrumentation,\n  inlineNotes,\n  commissionInfo\n\n  }\n}": WORKS_LISTING_QUERYResult;
  }
}
